### ISSUE TITLE
auth and some other requests were black holed on mac os x

### ISSUE THREAD

**Issue by patrickhafner** [renose/open-renose#3]
On Mac OS X (Lion), the following errors appears when i try to login or send some other requests:

> The request has been black-holed
> Error: The requested address '/renose/renose/users/login' was not found on this server.
> 
> Stack Trace
> # 0 /Users/Patrick/Sites/renose/renose/lib/Cake/Controller/Component/SecurityComponent.php(214): SecurityComponent-> > blackHole(Object(UsersController), 'csrf')
> # 1 [internal function]: SecurityComponent->startup(Object(UsersController))
> # 2 /Users/Patrick/Sites/renose/renose/lib/Cake/Utility/ObjectCollection.php(104): call_user_func_array(Array, Array)
> # 3 /Users/Patrick/Sites/renose/renose/lib/Cake/Controller/Controller.php(606): ObjectCollection->trigger('startup', Array)
> # 4 /Users/Patrick/Sites/renose/renose/lib/Cake/Routing/Dispatcher.php(101): Controller->startupProcess()
> # 5 /Users/Patrick/Sites/renose/renose/lib/Cake/Routing/Dispatcher.php(86): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
> # 6 /Users/Patrick/Sites/renose/renose/app/webroot/index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> # 7 {main}

**Comment by SWW13** [comment]
fixed
