### ISSUE TITLE
Kosten-Nutzen-Analyse

### ISSUE THREAD

**Issue by SWW13** [renose/open-renose#49]
Kosten-Nutzen-Analyse mit Berechung Break-Even-Point Analyse

**Comment by WhiteDwarf** [comment]
Alles noch Verschönern und dann ab Dafür!

**Comment by patrickhafner** [comment]
fullack

**Comment by WhiteDwarf** [comment]
Hab ein Diagramm  in der DropBOX (BEP-Diagram) Bitte noch in den bericht einbauen!
