### ISSUE TITLE
other solution for profile birthday field needed

### ISSUE THREAD

**Issue by patrickhafner** [renose/open-renose#91]
the usability of birthday datepicker is very bad (changing year - one click = one year). we need an other solution

**Comment by SWW13** [comment]
it's an normal inputbox, so you can easly write your birthday without picking, most people should know the exact date of there bithday...

**Comment by patrickhafner** [comment]
okay, but the field should be in german format (DD.MM.YYYY)

**Comment by SWW13** [comment]
on chrome dev (v22) it shows the correct format

**Comment by patrickhafner** [comment]
creepy :o
this is a screenshot of mine: http://media.patrickhafner.de/display/54495a7d00a19482ea3a167d49b3c7f27911984c
